add_newline = true

format = """
$os$directory$git_branch$git_status
$character"""

[directory]
style = "bold blue"
truncation_length = 3

[git_branch]
symbol = " "
style = "purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "yellow"
format = '([$modified$untracked]($style) )'
modified = "!${count}"
untracked = "?${count}"

[fill]
symbol = "·"
style = "dimmed blue"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"
style = "dimmed white"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[os]
disabled = false

[os.symbols]
Windows = ""
Ubuntu = "🐧 "
